  0         LOADL        0
  1         PUSH         1
  2         PUSH         1
  3         PUSH         1
  4         CALL         L10
  5         POP          3
  6         HALT   (0)   
  7  L10:   LOADL        11
  8         STORE        1[SB]
  9         LOAD         1[SB]
 10         CALL         putintnl
 11         LOAD         1[SB]
 12         LOADL        55
 13         CALL         add     
 14         STORE        2[SB]
 15         LOAD         2[SB]
 16         CALL         putintnl
 17         LOADL        1
 18         LOAD         3[LB]
 19         CALL         putintnl
 20         LOADL        2
 21         LOAD         3[LB]
 22         CALL         mult    
 23         LOAD         3[LB]
 24         CALL         add     
 25         LOADL        1
 26         CALL         sub     
 27         STORE        3[LB]
 28         LOAD         3[LB]
 29         CALL         putintnl
 30         LOADL        3
 31         CALL         putintnl
 32         LOAD         3[LB]
 33         LOADL        2
 34         CALL         eq      
 35         JUMPIF (0)   L11
 36         LOADL        4
 37         STORE        3[LB]
 38         JUMP         L12
 39  L11:   LOADL        1
 40         CALL         neg     
 41         STORE        3[LB]
 42  L12:   LOAD         3[LB]
 43         CALL         putintnl
 44         LOADL        0
 45  L13:   LOAD         4[LB]
 46         LOADL        5
 47         CALL         lt      
 48         JUMPIF (0)   L14
 49         LOAD         4[LB]
 50         LOADL        1
 51         CALL         add     
 52         STORE        4[LB]
 53         LOAD         4[LB]
 54         STORE        3[LB]
 55         JUMP         L13
 56  L14:   LOAD         3[LB]
 57         CALL         putintnl
 58         LOADL        -1
 59         LOADL        3
 60         CALL         newobj  
 61         LOADL        5
 62         LOAD         5[LB]
 63         LOADL        0
 64         CALL         fieldref
 65         CALL         add     
 66         STORE        3[LB]
 67         LOAD         5[LB]
 68         LOADL        0
 69         CALL         ne      
 70         JUMPIF (0)   L15
 71         LOAD         3[LB]
 72         LOADL        1
 73         CALL         add     
 74         STORE        3[LB]
 75         JUMP         L15
 76  L15:   LOAD         3[LB]
 77         CALL         putintnl
 78         LOAD         5[LB]
 79         LOADL        1
 80         LOADL        -1
 81         LOADL        2
 82         CALL         newobj  
 83         CALL         fieldupd
 84         LOAD         5[LB]
 85         LOADL        1
 86         CALL         fieldref
 87         LOADL        0
 88         LOADL        7
 89         CALL         fieldupd
 90         LOAD         5[LB]
 91         LOADL        1
 92         CALL         fieldref
 93         LOADL        0
 94         CALL         fieldref
 95         STORE        3[LB]
 96         LOAD         3[LB]
 97         CALL         putintnl
 98         LOAD         5[LB]
 99         LOADL        1
100         CALL         fieldref
101         LOADL        1
102         LOAD         5[LB]
103         CALL         fieldupd
104         LOAD         5[LB]
105         LOADL        1
106         CALL         fieldref
107         LOADL        1
108         CALL         fieldref
109         LOADL        0
110         LOAD         3[LB]
111         LOADL        1
112         CALL         add     
113         CALL         fieldupd
114         LOAD         5[LB]
115         LOADL        0
116         CALL         fieldref
117         STORE        3[LB]
118         LOAD         3[LB]
119         CALL         putintnl
120         RETURN (0)   1
